### ISSUE TITLE
BEATTest TestTimedOutException

### ISSUE THREAD

**Issue by errantlinguist** [articulab/MUF-inMind-April2017-master#10]
*(migrated from https://github.com/articulab/InMind-April2017-BEAT/issues/2)*

The following unit test in the submodule `sarabeat` fails when built as a Gradle subproject but not when built as a standalone project (i.e. cloned directly from https://github.com/articulab/InMind-April2017-BEAT).

	org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
		at java.util.Arrays.fill(Arrays.java:2881)
		at edu.stanford.nlp.parser.lexparser.ExhaustivePCFGParser.parse(ExhaustivePCFGParser.java:440)
		at edu.stanford.nlp.parser.lexparser.LexicalizedParserQuery.parseInternal(LexicalizedParserQuery.java:270)
		at edu.stanford.nlp.parser.lexparser.LexicalizedParserQuery.parse(LexicalizedParserQuery.java:637)
		at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:323)
		at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:254)
		at edu.stanford.nlp.pipeline.SentenceAnnotator.annotate(SentenceAnnotator.java:102)
		at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
		at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:660)
		at edu.cmu.inmind.multiuser.sara.component.beat.languageProcessing.StanfordTaggerLocal.process(StanfordTaggerLocal.java:76)
		at edu.cmu.inmind.multiuser.sara.component.beat.languageProcessing.LanguageModule.annotate(LanguageModule.java:1095)
		at edu.cmu.inmind.multiuser.sara.component.beat.languageProcessing.LanguageModule.transduce(LanguageModule.java:1138)
		at edu.cmu.inmind.multiuser.sara.component.beat.utilities.BeatModule.process(BeatModule.java:117)
		at edu.cmu.inmind.multiuser.sara.component.beat.BEAT.startProcess(BEAT.java:145)
		at edu.cmu.inmind.multiuser.sara.component.beat.BEATTest.beatTest(BEATTest.java:16)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
		at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.lang.Thread.run(Thread.java:748)

**Comment by errantlinguist** [comment]
Fixed in a6a75c6cda8dab8b65cd1c1e03e43575af90bbcf of [*InMind-April2017-BEAT*](https://github.com/articulab/InMind-April2017-BEAT)
