### ISSUE TITLE
Null object sent for MSG_START_DM by SaraOrchestrator

### ISSUE THREAD

**Issue by errantlinguist** [articulab/MUF-inMind-April2017-master#3]
When connecting with [the Java mock client](https://github.com/inmind-project/multiuser-mockclient) commit dff9a5ac5a7c216d1e041ca640469931cd0b3b0e, the system connects and the DialogOS DM is initiated, but the following error is printed to the demonstrator's console output:

	edu.cmu.inmind.multiuser.controller.exceptions.MultiuserException: You are posting a null object through the Blackboard. Please check that
		at edu.cmu.inmind.multiuser.controller.blackboard.BlackboardImpl.post(BlackboardImpl.java:118)
		at edu.cmu.inmind.multiuser.controller.blackboard.BlackboardImpl.post(BlackboardImpl.java:102)
		at edu.cmu.inmind.multiuser.sara.orchestrator.SaraOrchestrator.process(SaraOrchestrator.java:69)
		at edu.cmu.inmind.multiuser.controller.session.SessionImpl.process(SessionImpl.java:242)
		at edu.cmu.inmind.multiuser.controller.session.SessionImpl.run(SessionImpl.java:219)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	edu.cmu.inmind.multiuser.controller.exceptions.MultiuserException: You are posting a null object through the Blackboard. Please check that
		at edu.cmu.inmind.multiuser.controller.blackboard.BlackboardImpl.post(BlackboardImpl.java:118)
		at edu.cmu.inmind.multiuser.controller.blackboard.BlackboardImpl.post(BlackboardImpl.java:102)
		at edu.cmu.inmind.multiuser.sara.orchestrator.SaraOrchestrator.process(SaraOrchestrator.java:69)
		at edu.cmu.inmind.multiuser.controller.session.SessionImpl.process(SessionImpl.java:242)
		at edu.cmu.inmind.multiuser.controller.session.SessionImpl.run(SessionImpl.java:219)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	edu.cmu.inmind.multiuser.controller.exceptions.MultiuserException: You are posting a null object through the Blackboard. Please check that
		at edu.cmu.inmind.multiuser.controller.blackboard.BlackboardImpl.post(BlackboardImpl.java:118)
		at edu.cmu.inmind.multiuser.controller.blackboard.BlackboardImpl.post(BlackboardImpl.java:102)
		at edu.cmu.inmind.multiuser.sara.orchestrator.SaraOrchestrator.process(SaraOrchestrator.java:69)
		at edu.cmu.inmind.multiuser.controller.session.SessionImpl.process(SessionImpl.java:242)
		at edu.cmu.inmind.multiuser.controller.session.SessionImpl.run(SessionImpl.java:219)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	[33m2018-05-15 08:41:31,289 WARN    ExceptionLogger                - ExceptionHandleredu.cmu.inmind.multiuser.controller.exceptions.MultiuserException: You are posting a null object through the Blackboard. Please check that
		at edu.cmu.inmind.multiuser.controller.blackboard.BlackboardImpl.post(BlackboardImpl.java:118)
		at edu.cmu.inmind.multiuser.controller.blackboard.BlackboardImpl.post(BlackboardImpl.java:102)
		at edu.cmu.inmind.multiuser.sara.orchestrator.SaraOrchestrator.process(SaraOrchestrator.java:69)
		at edu.cmu.inmind.multiuser.controller.session.SessionImpl.process(SessionImpl.java:242)
		at edu.cmu.inmind.multiuser.controller.session.SessionImpl.run(SessionImpl.java:219)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)

	[m[32m2018-05-15 08:41:31,290 INFO    ExceptionLogger                - storing log file to logs/exceptions/1526388029142.log
	[m[33m2018-05-15 08:41:31,291 WARN    ExceptionLogger                - ExceptionHandleredu.cmu.inmind.multiuser.controller.exceptions.MultiuserException: You are posting a null object through the Blackboard. Please check that
		at edu.cmu.inmind.multiuser.controller.blackboard.BlackboardImpl.post(BlackboardImpl.java:118)
		at edu.cmu.inmind.multiuser.controller.blackboard.BlackboardImpl.post(BlackboardImpl.java:102)
		at edu.cmu.inmind.multiuser.sara.orchestrator.SaraOrchestrator.process(SaraOrchestrator.java:69)
		at edu.cmu.inmind.multiuser.controller.session.SessionImpl.process(SessionImpl.java:242)
		at edu.cmu.inmind.multiuser.controller.session.SessionImpl.run(SessionImpl.java:219)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)

In the class `edu.cmu.inmind.multiuser.sara.orchestrator.SaraOrchestrator`, the following null reference is passed to the blackboard:

     blackboard.post(this, ComponentMessageTypes.MSG_START_DM, null);

**Comment by errantlinguist** [comment]
Fixed in 4850867c27f372985cae4c1910fab6e2705503e7
